author: Dr_MadMan
database: false
description: "A plugin that enables easy server wide Hunger Games events.\r\n"
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.dr_madman.hungercraft.HungerCraft
name: HungerCraft
startup: postworld
version: '.1'
commands:
   teleport:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   startgame:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   stopgame:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   setborder:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   forcestart:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   kit:
      description: This is a demo command.
      usage: /<command> [player]
      permission: 
      permission-message: You don't have <permission>
   addkit:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>







